In [1]:
import torch
from simple_nn import load_model_definition

In [2]:
torch.manual_seed(42)
model = load_model_definition()
model.fc1.weight[0]

tensor([ 0.2418,  0.2625, -0.0741,  0.2905, -0.0693,  0.0638, -0.1540,  0.1857,
         0.2788, -0.2320], grad_fn=<SelectBackward0>)

In [3]:
torch.manual_seed(42)
model_2 = load_model_definition()
model_2.fc1.weight[0]

tensor([ 0.2418,  0.2625, -0.0741,  0.2905, -0.0693,  0.0638, -0.1540,  0.1857,
         0.2788, -0.2320], grad_fn=<SelectBackward0>)

In [4]:
local_model_path = './local_model/simple_nn_random.pt'
model.load_state_dict(torch.load(local_model_path))
model.eval()
model.fc1.weight[0]

tensor([ 0.0147,  0.0913,  0.1322, -0.0688, -0.1188,  0.1426, -0.1939, -0.2946,
        -0.1351, -0.2272], grad_fn=<SelectBackward0>)